tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:pk>/update_task/', views.update, name='update'),
    path('<str:pk>/detele/', views.delete, name='delete')
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks'))
]

tasks/models.py
from django.db import models


class Task(models.Model):
    nombre = models.CharField(max_length=200)
    realizada = models.BooleanField(default=False)
    creada = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    
    nombre = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Añade una nueva tarea ..'}))

    class Meta:

        model = Task
        fields = '__all__'

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task
from .forms import TaskForm


def index(request):
    tasks = Task.objects.all()
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('tasks:index')

    context = {'tasks': tasks, 'form': form}
    return render(request, 'tasks/index.html', context)


def update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        return redirect('tasks:index')

    context = {'form': form}
    return render(request, 'tasks/update.html', context)


def delete(request, pk):
    task = get_object_or_404(Task, pk=pk)

    if request.method == 'POST':
        task.delete()
        return redirect('tasks:index')

    context = {'task': task}
    return render(request, 'tasks/delete.html', context)

templates/tasks/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <!-- Google Font: Noto Sans JP -->
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">

        {% load static %}
        <!-- Personal CSS -->
        <link href="{% static 'polls/style.css' %}" rel="stylesheet">

        <title>Todo App made with Django</title>
    </head>
    <body>
        <div class="center-column">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/tasks/delete.html
{% extends 'tasks/base.html' %}

{% block content %}
<h3 class="text-center font-weight-bold">¿Estás seguro que deseas borrar <mark>"{{ task }}"?</mark></h3>
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" name="delete task" value="Borrar">
        <a class="btn btn-primary btn-block" href="{% url 'tasks:index' %}">Cancelar</a>
    </form>
{% endblock %}

templates/tasks/index.html
{% extends 'tasks/base.html' %}
{% block content %}
    <div class="container">

        <h3 class="text-center font-weight-bold">Agregar tarea</h3>

        <form method="POST">
            {% csrf_token %}
            {{ form.nombre }}
            <input class="btn btn-primary btn-block" type="submit" name="create task" value="Crear">
        </form>
        <hr/>

        {% for task in tasks %}
        <div class="item-row">
            <a class="btn btn-sm btn-info" href="{% url 'tasks:update' task.id %}">Actualizar</a>
            <a class="btn btn-sm btn-danger" href="{% url 'tasks:delete' task.id %}">Borrar</a>
            {% if task.realizada %}
                <strike>{{ task }}</strike>
            {% else %}
                <span>{{ task }}</span>
            {% endif %}

        </div>
        {% endfor %}

    </div>
{% endblock %}

templates/tasks/update.html
{% extends 'tasks/base.html' %}
{% block content %}
    <h3 class="text-center font-weight-bold">Actualizar Tarea</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-primary" type="submit" name="update task" value="Actualizar">
    </form>
{% endblock %}